### ISSUE TITLE
Android crashes with: RNIapModule.buyItemByType got 8 arguments, expected 7

### ISSUE THREAD

**Issue by jedashford** [iaphub/react-native-iaphub#27]
We've had our android implementation working fine, but out of the blue we're now getting a crash when trying to use `await Iaphub.buy(sku)`

Versions:
`    "react-native-iap": "^4.6.3",
    "react-native-iaphub": "^4.1.3",`

```09-26 19:08:31.188  8531  8950 E unknown:ReactNative: CatalystInstanceImpl caught native exception
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: com.facebook.react.bridge.NativeArgumentsParseException: RNIapModule.buyItemByType got 8 arguments, expected 7
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:873)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:193)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: Exception in native call
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: com.facebook.react.bridge.NativeArgumentsParseException: RNIapModule.buyItemByType got 8 arguments, expected 7
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:873)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:193)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
09-26 19:08:31.188  8531  8950 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)```

**Comment by iaphub** [comment]
Seems like you updated to the latest version of react-native-iap which is using In-app billing V3.
The latest version of react-native-iaphub is still using the In-app billing V2, we'll upgrade it in the next release coming soon.
Downgrade react-native-iap to v4.5.3 and the error should disappear 👍

**Comment by jedashford** [comment]
Haha, I just narrowed it down to:
node_modules/react-native-iaphub/src/index.js
```RNIap.requestSubscription(product.sku, false);```

So was going to go investigate there. I'll downgrade now and give it a shot, thanks for the late night Saturday help.

**Comment by iaphub** [comment]
Happy to help, closing the issue but you can still reply back if you still have the problem.

**Comment by jedashford** [comment]
This was the issue, its now fixed. Thanks again.
